
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerloadable_1ModuleWidgets_h
#define __osm_qSlicerloadable_1ModuleWidgets_h

#include <QObject>
#include "qSlicerloadable_1FooBarWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerloadable_1FooBarWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerloadable_1FooBarWidget* new_qSlicerloadable_1FooBarWidget(QWidget*  parent = 0)
    {
    return new qSlicerloadable_1FooBarWidget(parent);
    }
  void delete_qSlicerloadable_1FooBarWidget(qSlicerloadable_1FooBarWidget* obj) { delete obj; }
};

#endif
