# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget vtkSlicerloadable_1ModuleLogic vtkSlicerloadable_1ModuleLogicPython qSlicerloadable_1ModuleWidgets)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target vtkSlicerloadable_1ModuleLogic
add_library(vtkSlicerloadable_1ModuleLogic SHARED IMPORTED)

set_target_properties(vtkSlicerloadable_1ModuleLogic PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkdouble-conversion;ITKInternalEigen3::Eigen;itksys;TBB::tbb;itkvnl_algo;itkvnl;itkv3p_netlib;itkvcl;ITKCommon;itkNetlibSlatec;ITKStatistics;ITKTransform;ITKMesh;C:/D/S4R/zlib-install/lib/zlib.lib;ITKMetaIO;ITKSpatialObjects;ITKSmoothing;AdaptiveDenoising;ITKIOImageBase;IOScanco;ITKPath;ITKLabelMap;ITKMathematicalMorphology;ITKQuadEdgeMesh;ITKFastMarching;ITKImageFeature;ITKOptimizers;ITKPolynomials;ITKBiasCorrection;ITKColormap;ITKFFT;ITKConvolution;ofstd;oflog;dcmdata;i2d;dcmimgle;dcmimage;dcmjpeg;ijg8;ijg12;ijg16;dcmjpls;dcmtkcharls;dcmtls;dcmnet;dcmsr;cmr;dcmdsig;dcmwlm;dcmqrdb;dcmpstat;dcmrt;dcmiod;dcmfg;dcmseg;dcmtract;dcmpmap;dcmect;ITKDICOMParser;ITKDeformableMesh;ITKDenoising;ITKDeprecated;ITKDiffusionTensorImage;ITKEXPAT;gdcmDICT;gdcmMSFF;ITKznz;ITKniftiio;ITKgiftiio;ITKPDEDeformableRegistration;hdf5_cpp-shared;hdf5-shared;ITKIOBMP;ITKIOBioRad;ITKIOBruker;ITKIOCSV;ITKIODCMTK;ITKIOGDCM;ITKIOIPL;ITKIOGE;ITKIOGIPL;ITKIOHDF5;itkjpeg;ITKIOJPEG;itkopenjpeg;ITKIOJPEG2000;itktiff;ITKIOTIFF;ITKIOLSM;itkminc2;ITKIOMINC;ITKIOMRC;ITKIOMeshBase;ITKIOMeshBYU;ITKIOMeshFreeSurfer;ITKIOMeshGifti;ITKIOMeshOBJ;ITKIOMeshOFF;ITKIOMeshVTK;ITKIOMeta;ITKIONIFTI;ITKNrrdIO;ITKIONRRD;itkpng;ITKIOPNG;ITKIOSiemens;ITKIOXML;ITKIOSpatialObjects;ITKIOStimulate;ITKTransformFactory;ITKIOTransformBase;ITKIOTransformHDF5;ITKIOTransformInsightLegacy;ITKIOTransformMatlab;ITKIOVTK;ITKKLMRegionGrowing;itklbfgs;ITKMarkovRandomFieldsClassifiers;ITKOptimizersv4;ITKQuadEdgeMeshFiltering;ITKRegionGrowing;ITKRegistrationMethodsv4;ITKVTK;ITKWatersheds;ITKReview;ITKTestKernel;ITKVideoCore;ITKVideoIO;ITKVtkGlue;MGHIO;SimpleITKFilters;ITKFactoryRegistration;qSlicerBaseQTCLI;SlicerBaseLogic;MRMLDisplayableManager"
)

# Create imported target vtkSlicerloadable_1ModuleLogicPython
add_library(vtkSlicerloadable_1ModuleLogicPython MODULE IMPORTED)

# Create imported target qSlicerloadable_1ModuleWidgets
add_library(qSlicerloadable_1ModuleWidgets SHARED IMPORTED)

set_target_properties(qSlicerloadable_1ModuleWidgets PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkSlicerloadable_1ModuleLogic;qSlicerBaseQTApp"
)

# Import target "vtkSlicerloadable_1ModuleLogic" for configuration "Debug"
set_property(TARGET vtkSlicerloadable_1ModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkSlicerloadable_1ModuleLogic PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerloadable_1ModuleLogic.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerloadable_1ModuleLogic.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogicPython" for configuration "Debug"
set_property(TARGET vtkSlicerloadable_1ModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(vtkSlicerloadable_1ModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_DEBUG ""
  IMPORTED_LOCATION_DEBUG "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Debug/vtkSlicerloadable_1ModuleLogicPython.pyd"
  )

# Import target "qSlicerloadable_1ModuleWidgets" for configuration "Debug"
set_property(TARGET qSlicerloadable_1ModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(qSlicerloadable_1ModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Debug/qSlicerloadable_1ModuleWidgets.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Debug/qSlicerloadable_1ModuleWidgets.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogic" for configuration "Release"
set_property(TARGET vtkSlicerloadable_1ModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkSlicerloadable_1ModuleLogic PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerloadable_1ModuleLogic.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerloadable_1ModuleLogic.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogicPython" for configuration "Release"
set_property(TARGET vtkSlicerloadable_1ModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(vtkSlicerloadable_1ModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Release/vtkSlicerloadable_1ModuleLogicPython.pyd"
  )

# Import target "qSlicerloadable_1ModuleWidgets" for configuration "Release"
set_property(TARGET qSlicerloadable_1ModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(qSlicerloadable_1ModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Release/qSlicerloadable_1ModuleWidgets.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/Release/qSlicerloadable_1ModuleWidgets.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogic" for configuration "MinSizeRel"
set_property(TARGET vtkSlicerloadable_1ModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkSlicerloadable_1ModuleLogic PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerloadable_1ModuleLogic.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerloadable_1ModuleLogic.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogicPython" for configuration "MinSizeRel"
set_property(TARGET vtkSlicerloadable_1ModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(vtkSlicerloadable_1ModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_MINSIZEREL ""
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/vtkSlicerloadable_1ModuleLogicPython.pyd"
  )

# Import target "qSlicerloadable_1ModuleWidgets" for configuration "MinSizeRel"
set_property(TARGET qSlicerloadable_1ModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(qSlicerloadable_1ModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/qSlicerloadable_1ModuleWidgets.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/MinSizeRel/qSlicerloadable_1ModuleWidgets.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogic" for configuration "RelWithDebInfo"
set_property(TARGET vtkSlicerloadable_1ModuleLogic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkSlicerloadable_1ModuleLogic PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerloadable_1ModuleLogic.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerloadable_1ModuleLogic.dll"
  )

# Import target "vtkSlicerloadable_1ModuleLogicPython" for configuration "RelWithDebInfo"
set_property(TARGET vtkSlicerloadable_1ModuleLogicPython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(vtkSlicerloadable_1ModuleLogicPython PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELWITHDEBINFO ""
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/vtkSlicerloadable_1ModuleLogicPython.pyd"
  )

# Import target "qSlicerloadable_1ModuleWidgets" for configuration "RelWithDebInfo"
set_property(TARGET qSlicerloadable_1ModuleWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(qSlicerloadable_1ModuleWidgets PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/qSlicerloadable_1ModuleWidgets.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Leonard/code/loadable_1/lib/Slicer-4.13/qt-loadable-modules/RelWithDebInfo/qSlicerloadable_1ModuleWidgets.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
