
set(Slicer_CMAKE_DIR "C:/D/S4/CMake")
set(SLICER_EXTENSION_MANAGER_CLIENT_EXECUTABLE "SLICER_EXTENSION_MANAGER_CLIENT_EXECUTABLE-NOTDEFINED")
set(SLICER_EXTENSION_MANAGER_URL "SLICER_EXTENSION_MANAGER_URL-NOTDEFINED")
set(SLICER_EXTENSION_MANAGER_API_KEY "SLICER_EXTENSION_MANAGER_API_KEY-NOTDEFINED")
set(CTEST_MODEL "Experimental")
set(Slicer_REVISION "30510")
set(EXTENSION_NAME "loadable_1")
set(EXTENSION_CATEGORY "Examples")
set(EXTENSION_ICONURL "https://www.example.com/Slicer/Extensions/loadable_1.png")
set(EXTENSION_CONTRIBUTORS "John Doe (AnyWare Corp.)")
set(EXTENSION_DEPENDS "NA")
set(EXTENSION_DESCRIPTION "This is an example of a simple extension")
set(EXTENSION_HOMEPAGE "https://www.slicer.org/wiki/Documentation/Nightly/Extensions/loadable_1")
set(EXTENSION_SCREENSHOTURLS "https://www.example.com/Slicer/Extensions/loadable_1/Screenshots/1.png")
set(EXTENSION_ENABLED "1")
set(EXTENSION_OPERATING_SYSTEM "win")
set(EXTENSION_ARCHITECTURE "amd64")
set(EXTENSION_WC_TYPE "local")
set(EXTENSION_WC_URL "NA")
set(EXTENSION_WC_REVISION "100")
set(EXTENSION_BINARY_DIR "C:/Users/Leonard/code/loadable_1/.")