# CMake generated Testfile for 
# Source directory: C:/Users/Leonard/code/loadable_1/loadable_1
# Build directory: C:/Users/Leonard/code/loadable_1/loadable_1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[qSlicerloadable_1ModuleGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/Debug/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[qSlicerloadable_1ModuleGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/Release/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[qSlicerloadable_1ModuleGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/MinSizeRel/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[qSlicerloadable_1ModuleGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/RelWithDebInfo/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
else()
  add_test([=[qSlicerloadable_1ModuleGenericTest]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[qSlicerloadable_1ModuleWidgetGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/Debug/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleWidgetGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleWidgetGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[qSlicerloadable_1ModuleWidgetGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/Release/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleWidgetGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleWidgetGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[qSlicerloadable_1ModuleWidgetGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/MinSizeRel/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleWidgetGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleWidgetGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[qSlicerloadable_1ModuleWidgetGenericTest]=] "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-additional-settings" "C:/Users/Leonard/code/loadable_1/AdditionalLauncherSettings.ini" "--launch" "C:/Users/Leonard/code/loadable_1/bin/RelWithDebInfo/qSlicerloadable_1ModuleGenericCxxTests.exe" "qSlicerloadable_1ModuleWidgetGenericTest")
  set_tests_properties([=[qSlicerloadable_1ModuleWidgetGenericTest]=] PROPERTIES  LABELS "qSlicerloadable_1Module" _BACKTRACE_TRIPLES "C:/D/S4/CMake/SlicerMacroBuildLoadableModule.cmake;293;add_test;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;49;slicerMacroBuildLoadableModule;C:/Users/Leonard/code/loadable_1/loadable_1/CMakeLists.txt;0;")
else()
  add_test([=[qSlicerloadable_1ModuleWidgetGenericTest]=] NOT_AVAILABLE)
endif()
subdirs("Logic")
subdirs("Widgets")
subdirs("Testing")
